### ISSUE TITLE
Cannot compile in Windows

### ISSUE THREAD

**Issue by edgarsilva** [creationix/node-gamepad#1]
Hi @creationix,

I'm trying to compile in all platforms so we can add pre-compiled binaries, using node-pre-gyp, for all major platforms, but I keep getting this error:

```
C:\projects\cylon-joystick\node_modules\gamepad\gamepad\source\gamepad/Gamepad.h(29): fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory [C:\projects\cylon-joystick\node_modules\gamepad\build\gamepad.vcxproj]
```

I'm currently using appveyor and a windows machine, I only see this problem in windows platforms, works well in linux and OSX as far as I can tell. Wondering if you know what the issue might be.

**Comment by RangerMauve** [comment]
Has this been closed?

**Comment by creationix** [comment]
I think this is solved now.  I've used this just fine on windows out of the box.
