### ISSUE TITLE
No "attach" events are emitted

### ISSUE THREAD

**Issue by Lange** [creationix/node-gamepad#14]
Hi there!

I've just discovered this library, and it's fantastic! However, it seems that I'm not receiving any `attach` events. Here is my code:
```js
const gamepad = require('gamepad');

gamepad.on('attach', (id, state) => {
	console.log('attach', {id, state});
});

gamepad.init();

// Create a game loop and poll for events
setInterval(gamepad.processEvents, 16);
// Scan for new gamepads as a slower rate
setInterval(gamepad.detectDevices, 500);

// Listen for button 0 down event from our target gamepad.
gamepad.on('down', (id, num) => {
	if (num !== 0) {
		return;
	}

	const device = gamepad.deviceAtIndex(id);
	if (device.vendorID === 9025 && device.productID === 32845) {
		console.log('down', {
			id,
			num
		});
	}
});
```

I have yet to see a log message from the `attach` event, even though I can receive gamepad `down` events just fine.

In addition, this code throws an uncaught exception if I unplug and re-plug my controller and press button `0` again, because the new device doesn't seem to be returned when calling `gamepad.deviceAtIndex(id)`.

Thanks for your time and this lovely library!
Alex

EDIT: This is on Windows 10, Node v6.9.1

**Comment by creationix** [comment]
I wonder if the underlying library doesn't support attach events on all platforms.  You can use a `setInterval` to poll to simulate in this case.

**Comment by Lange** [comment]
Do you mean using `setInterval` to poll `gamepad.detectDevices`? My code snippet above does indeed include that, but it seems that `gamepad`'s internal list of devices is still not updated. If I unplug my device and plug it back in, I still receive all input events from that device, but attempting to call `gamepad.deviceAtIndex` on the new device `id` will result in an error. I also never receive `attach` events at any point, even when first starting up the program.

**Comment by creationix** [comment]
Ahh, I see.  I wonder if it doesn't support hotplug at all then.  I found this in the original thread for the underlying library.  https://forums.tigsource.com/index.php?topic=10675.msg1129557#msg1129557

I was developing this back in 2014 so there is a chance I missed this bugfix.

You're welcome to submit a PR with the proposed fix in the thread if that fixes things for you.

**Comment by creationix** [comment]
Also see https://github.com/ThemsAllTook/libstem_gamepad/commit/b123e7a94e7a829d7b090270f6dd7fd1c8ccf607

**Comment by Lange** [comment]
Ah, thank you for these links! I'm out of town for two weeks but I may create a PR for this when I return, as it seems trivial to implement.

**Comment by creationix** [comment]
Awesome!

**Comment by creationix** [comment]
When you do get back, just update my library to match the version in the github repo.  There may be other bug fixes I've missed as well.

**Comment by creationix** [comment]
Nevermind, I just updated it myself.

Try the new 1.4.2 version on npm.   I think something might be wrong with the prebuilt binaries, but otherwise it seems to be working.

**Comment by Lange** [comment]
Thank you so much for taking the time to update this! The prebuilt libraries did indeed not work, but I was able to build them just fine during `npm install`. Aside from that, everything is working just fine. I'm seeing `attach` events.

We'll be using this library to help interface with some of the custom hardware being used for [Awesome Games Done Quick](https://gamesdonequick.com/), a charity fundraiser benefitting the Prevent Cancer Foundation coming up in a few days. Thanks again!
