### ISSUE TITLE
Move binary publishing to Github and off S3 bucket

### ISSUE THREAD

**Issue by deadprogram** [creationix/node-gamepad#17]
We should move the hosting of the precompiled binaries off of the S3 bucket that we are curringly hosting, and onto Github.

**Comment by creationix** [comment]
Fine with me.

**Comment by deadprogram** [comment]
Can someone take this on? https://github.com/bchr02/node-pre-gyp-github should work.

**Comment by Lange** [comment]
You may also have success with https://github.com/prebuild/prebuild.

[`node-serialport`](https://github.com/node-serialport/node-serialport)'s CI configs ([`appveyor.yml`](https://github.com/node-serialport/node-serialport/blob/master/appveyor.yml) and [`.travis.yml`](https://github.com/node-serialport/node-serialport/blob/master/.travis.yml)) are great examples of how to set up `prebuild` in CI.

Additionally, this PR to `node-usb-detection` (https://github.com/MadLittleMods/node-usb-detection/pull/47) gives a nice clear outline of the whole process for getting `prebuild` up and running on an existing project.

**Comment by deadprogram** [comment]
@Lange your PR here would be greatly appreciated. I do not have time to work on this at present, but we'd like to not have to pay for the S3 hosting when Github is happy to host the binaries. :)

**Comment by Lange** [comment]
@deadprogram I'm unsure that I have the time either, though if I do find it I would be happy to contribute. Failing that, hopefully the links in my previous post can act as a guide for another contributor.

**Comment by Lange** [comment]
I've started looking into implementing `prebuild` for this project. However, you'd lose some functionality in doing so.

Specifically, there's a bit of the `script` stanza at [.travis.yml#L53](https://github.com/creationix/node-gamepad/blob/master/.travis.yml#L53) which unpublishes the binary in the event that installing the just-published binary fails. I don't think this is easily replicable with `prebuild`. It certainly _could_ be done with some manual API requests via `curl` or something though.

How critical is this bit of the script, in your opinion? Would you be okay with it being removed as part of a migration to `prebuild`?

**Comment by creationix** [comment]
I think it's fine without the custom unpublish hook.
