### ISSUE TITLE
Compilation Fails on Node v0.12.0 and io.js

### ISSUE THREAD

**Issue by stewart** [creationix/node-gamepad#5]
Changed APIs in Node v0.11 mean that this module can't compile on newer versions of Node or io.js.

A possible solution is to use https://github.com/rvagg/nan.

Example build failure: https://travis-ci.org/hybridgroup/cylon-joystick/jobs/57512982#L370.

**Comment by creationix** [comment]
Porting to nan would be awesome.  I don't have time at the moment to do it myself though.  I'll get to it later if nobody beats me to it.
