### ISSUE TITLE
Electron

### ISSUE THREAD

**Issue by Ajusa** [creationix/node-gamepad#9]
This doesn't appear to install, or work with electron. It works in other projects on the same machine..
Here is a log. Help would be appreciated
http://pastebin.com/9KKWUKCD

**Comment by Ajusa** [comment]
Actually, I got it to install using node 0.12.7. However, when I run it, it gives me the error of "Cannot find node_modules\gamepad\build\gamepad\v1.1.0\Release\node-v0.12.7-win32-x64\gamepad.node"
Instead, the file name is "node_modules\gamepad\build\gamepad\v1.1.0\Release\node-v14-win32-x64\gamepad.node"
Why are the 14 and 12 different? Also, changing the directory name gives the error of "Module did not self register"

**Comment by RangerMauve** [comment]
If you're in Electron, why not use the [web gamepad api](https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API/Using_the_Gamepad_API)?

**Comment by Ajusa** [comment]
Because I am an idiot... XD
I forgot that that existed. The issue of gamepad not installing/working is still valid however...
I will close the issue, as you fixed my problem. Thanks!

**Comment by KuhlTime** [comment]
I got the same issue as @Ajusa. Is there a way to fix that and get gamepad running inside electron?

**Comment by gamelaster** [comment]
You must build by:
```
cd node_modules\gamepad\
node-pre-gyp install --runtime=electron --fallback-to-build
```
